version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: 03032006
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  todo-app:
    build: .
    env_file: 
      - .env  
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_PASSWORD: 03032006
    command: ["./wait-for-postgres.sh", "db", "5432", "./todo-app"]

volumes:
  postgres_data: